# Generated by Django 4.1.1 on 2022-09-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrioritySchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.TextField()),
                ('category_values', models.TextField()),
                ('priority_index', models.TextField()),
            ],
        ),
    ]
